version: "3"
services:
  api:
    build: .
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=dJhC4VnRuYThfyWu8I6RtU6d5h94WaBXxveylJmu8Tx8kPCRKt17mdSuYcHbAAth0fv8DAeebUCGpebIPz63168QBjxJz4kVPCsKnoT1Oh7QRvFWiMpNsCIYP87odjVuHpbf2kO6aztUjXDa8NEA0XuxosoUwNR8fltuM6wOcvoHJByJ3OzSs1k6MLqWxZOFBGfbF8IxprnFYQEBFmT2IPRgJIYnPtGEY2up3aMhfcru5eaThrNTY0kJVwJ2bK05cmpNqUzSm72ojjB2gJmAxs62IDSaU1QJH2Muj2WNPUSLfeA5OcVxeILqvKeOC7C6
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
